# Site settings
title: 謎
#email: 6ra@hanarchy.biz
description: 謎です
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

gems: [jekyll-paginate, jekyll-feed]
exclude: ["README.md", "LISENCE", "CNAME"]

author: 6RA
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hanarchy_biz
github_username: hanarchy
permalink: /blog/:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
# viewsourceroot: https://github.com/LiXizhi/LiXizhi.github.io/blob/master/
# this is the url root of the create page link on the footer page.
# newsourceroot: https://github.com/LiXizhi/LiXizhi.github.io/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: hanarchy
disqus_url: "http://hanarchy.disqus.com"
#########################################

default_aside: [aside/about.html, aside/recent_posts.html]


# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false


paginate: 5
paginate_path: "blog/page:num"
recent_posts: 5
excerpt_link: "Read more"
excerpt_separator: "<!-- more -->"